import { Link, useParams } from "react-router-dom";
import { ArrowUpRight, CheckCircle2, Clock3, Download, QrCode, Ticket, UsersRound } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useEventDashboard } from "@/hooks/useEventDashboard";
import { EventTabs, PageHeader } from "@/components/PageHeader";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

export function EventOverviewPage() {
  const { eventId = "" } = useParams();
  const query = useEventDashboard(eventId);
  const event = query.data?.event;
  const summary = query.data?.summary;
  if (query.isLoading) return <div className="space-y-4"><div className="h-8 w-52 animate-pulse rounded bg-muted" /><div className="h-36 animate-pulse rounded-2xl bg-muted" /></div>;
  if (query.isError || !event || !summary) return <Card><CardContent className="p-8 text-sm text-destructive">This event is unavailable or you don't have access.</CardContent></Card>;
  const metrics = [{ label: "Registered guests", value: summary.total, icon: UsersRound, tone: "bg-blue-50 text-blue-700" }, { label: "Checked in", value: summary.checkedIn, icon: CheckCircle2, tone: "bg-emerald-50 text-emerald-700" }, { label: "Still expected", value: summary.remaining, icon: Clock3, tone: "bg-amber-50 text-amber-800" }, { label: "Arrival rate", value: `${summary.rate}%`, icon: Ticket, tone: "bg-violet-50 text-violet-700" }];
  return <div className="page-enter"><PageHeader eyebrow="Event / live operations" title={event.name} description={[event.startsAt ? new Date(event.startsAt).toLocaleString() : "Date not set", event.venue].filter(Boolean).join(" · ")} action={<div className="flex gap-2"><Link to={`/admin/events/${eventId}/links`}><Button variant="outline" size="sm"><QrCode className="h-4 w-4" />Scanner link</Button></Link><Link to={`/admin/events/${eventId}/attendees`}><Button size="sm"><UsersRound className="h-4 w-4" />Add attendee</Button></Link></div>} /><EventTabs eventId={eventId} />
    <div className="mb-6 flex items-center gap-2 text-xs text-muted-foreground"><span className="relative flex h-2 w-2"><span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-emerald-400 opacity-50" /><span className="relative inline-flex h-2 w-2 rounded-full bg-emerald-500" /></span>Live updates are on <span className="text-border">/</span> refreshes from the event stream</div>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map((metric) => <Card key={metric.label}><CardContent className="flex items-start justify-between p-5"><div><p className="label-caps">{metric.label}</p><p className="mt-3 font-display text-3xl font-semibold tabular-nums tracking-tight">{metric.value}</p></div><div className={`grid h-10 w-10 place-items-center rounded-xl ${metric.tone}`}><metric.icon className="h-5 w-5" /></div></CardContent></Card>)}</section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.45fr_.8fr]">
      <Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Arrivals over time</CardTitle><p className="mt-1 text-xs text-muted-foreground">Check-ins recorded in the last 12 hours</p></div><Badge tone="success">{summary.rate}% complete</Badge></CardHeader><CardContent><div className="h-[250px] w-full">{summary.hourly.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={summary.hourly} margin={{ top: 8, right: 8, bottom: 0, left: -20 }}><defs><linearGradient id="arrivalFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3468dc" stopOpacity={0.2} /><stop offset="95%" stopColor="#3468dc" stopOpacity={0.01} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e8edf3" /><XAxis dataKey="hour" axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: "#7d8797" }} /><YAxis allowDecimals={false} axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: "#7d8797" }} /><Tooltip contentStyle={{ borderRadius: 12, border: "1px solid #e4e9ef", fontSize: 12 }} /><Area type="monotone" dataKey="count" name="Check-ins" stroke="#3468dc" strokeWidth={2.5} fill="url(#arrivalFill)" /></AreaChart></ResponsiveContainer> : <div className="grid h-full place-items-center rounded-xl border border-dashed border-border text-sm text-muted-foreground">Check-ins will appear here as guests arrive.</div>}</div></CardContent></Card>
      <Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Latest arrivals</CardTitle><p className="mt-1 text-xs text-muted-foreground">Most recent scans</p></div><Link to={`/admin/events/${eventId}/analytics`} className="inline-flex items-center gap-1 text-xs font-semibold text-primary">Full analytics <ArrowUpRight className="h-3.5 w-3.5" /></Link></CardHeader><CardContent className="pt-1">{summary.recentCheckIns.length ? <div className="divide-y divide-border">{summary.recentCheckIns.map((guest) => <div key={guest.id} className="flex items-center gap-3 py-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-emerald-50 text-[11px] font-bold text-emerald-800">{guest.name.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{guest.name}</p><p className="mt-0.5 text-[11px] text-muted-foreground">{guest.ticketType}</p></div><span className="shrink-0 font-mono text-[10px] text-muted-foreground">{guest.checkedInAt ? new Date(guest.checkedInAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : "—"}</span></div>)}</div> : <p className="py-10 text-center text-sm text-muted-foreground">No check-ins yet.</p>}</CardContent></Card>
    </section>
    <div className="mt-5 grid gap-4 md:grid-cols-2"><Link to={`/admin/events/${eventId}/designer`} className="group"><Card className="h-full transition-all group-hover:shadow-lift"><CardContent className="flex items-center gap-4 p-5"><div className="grid h-11 w-11 place-items-center rounded-xl bg-indigo-50 text-indigo-700"><Ticket className="h-5 w-5" /></div><div className="flex-1"><h3 className="font-semibold">Design event badges</h3><p className="mt-1 text-xs text-muted-foreground">Position QR, guest name and ticket details on your PDF.</p></div><Download className="h-4 w-4 text-muted-foreground" /></CardContent></Card></Link><Link to={`/admin/events/${eventId}/links`} className="group"><Card className="h-full transition-all group-hover:shadow-lift"><CardContent className="flex items-center gap-4 p-5"><div className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><QrCode className="h-5 w-5" /></div><div className="flex-1"><h3 className="font-semibold">Open the scanner desk</h3><p className="mt-1 text-xs text-muted-foreground">Create a staff-only link for the entrance team.</p></div><ArrowUpRight className="h-4 w-4 text-muted-foreground" /></CardContent></Card></Link></div>
  </div>;
}
